{{- if eq .Values.type "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.nameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.nameOverride }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Values.nameOverride }}
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Values.nameOverride }}
      name: {{ .Values.nameOverride }}
    spec:
      containers:
        - name: server
          command:
            - /opt/nautobot/bin/nautobot-server
            - start
            - --config-path
            - .nautobot/nautobot_config.py
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: {{ .Values.config.scheduler.broker }}
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.scheduler.results }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              value: {{ .Values.database.engine }}
            - name: NAUTOBOT_DB_HOST
              value: postgres.database.svc.cluster.local
            - name: NAUTOBOT_DB_NAME
              value: {{ .Values.database.database }}
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret.{{ .Values.database.name }}
                  key: password
            - name: NAUTOBOT_DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret.{{ .Values.database.name }}
                  key: username
            - name: NAUTOBOT_ROOT
              value: {{ .Values.config.root }}
            - name: NAUTOBOT_REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: NAUTOBOT_REDIS_SCHEME
              value: redis
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_SUPERUSER_USERNAME
              value: {{ .Values.superUser.username }}
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
              name: nautobot
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: {{ .Values.config.name }}
              mountPath: /opt/nautobot/
        - name: scheduler
          command:
            - /opt/nautobot/bin/nautobot-server
            - celery
            - --config
            - .nautobot/nautobot_config.py
            - beat
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: {{ .Values.config.scheduler.broker }}
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.scheduler.results }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              value: {{ .Values.database.engine }}
            - name: NAUTOBOT_DB_HOST
              value: postgres.database.svc.cluster.local
            - name: NAUTOBOT_DB_NAME
              value: {{ .Values.database.database }}
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret.{{ .Values.database.name }}
                  key: password
            - name: NAUTOBOT_DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret.{{ .Values.database.name }}
                  key: username
            - name: NAUTOBOT_ROOT
              value: {{ .Values.config.scheduler.root }}
            - name: NAUTOBOT_REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: NAUTOBOT_REDIS_SCHEMEspec.template.spec.containers
              value: redis
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_USERNAME
              value: {{ .Values.superUser.username }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          image: "{{ .Values.config.scheduler.img.repository }}:{{ .Values.config.scheduler.img.tag }}"
          ports:
            - containerPort: 5673
              name: celery
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: {{ .Values.config.name }}
              mountPath: /opt/nautobot/
        - name: worker
          command:
            - /bin/bash
            - '-c'
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: {{ .Values.config.worker.broker }}
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              value: {{ .Values.database.engine }}
            - name: NAUTOBOT_DB_HOST
              value: postgres.database.svc.cluster.local
            - name: NAUTOBOT_DB_NAME
              value: {{ .Values.database.database }}
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: {{ .Values.config.worker.root }}
            - name: NAUTOBOT_REDIS_HOST
              value: redis.database.svc.cluster.local
            - name: NAUTOBOT_REDIS_SCHEME
              value: redis
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_USERNAME
              value: {{ .Values.superUser.username }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          image: "{{ .Values.config.worker.img.repository }}:{{ .Values.config.worker.img.tag }}"
          ports:
            - containerPort: 5672
              name: worker
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: {{ .Values.config.name }}
              mountPath: /opt/nautobot/.nautobot
      volumes:
        - name: {{ .Values.config.name }}
          configMap:
            name: {{ .Values.config.name }}
        - name: nautobot
          persistentVolumeClaim:
            claimName: nautobot
{{- end -}}

