---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http
spec:
  hostnames:
  - grafana.breeze-blocks.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: grafana
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
    # timeouts:
    #   request: "2s"
