repos:
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.30.0
  #   hooks:
  #     - id: gitleaks
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.5 # Replace with latest tag
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
