---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  parentRefs:
    - name: {{ .Release.Name }}
  hostnames:
  {{ range $.Values.server.route.main.hostnames }}
    - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}
          port: 80
        - name: {{ .Release.Name }}
          port: 443
