---
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    labels:
      app.kubernetes.io/name: prometheus
    namespace: monitoring
  spec:
    hostnames:
    - prometheus.breeze-blocks.net
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: prometheus-gateway
    rules:
    - backendRefs:
      # - group: ""
      #   kind: Service
      #   name: prometheus-svc
      #   port: 9090
      #   weight: 1
      - kind: Service
        name: prometheus
        port: 9090
      matches:
      - path:
          type: PathPrefix
          value: /
